[package]
name = "akita"
version = "0.1.3"
authors = ["mrpan <1049058427@qq.com>"]
edition = "2018"
description = "Akita.Mini Database Helper For MySQL."
readme = "README.md"
keywords = ["akita", "mysql", "sql"]
categories = ["data-structures", "database-implementations"]
homepage = "https://github.com/wslongchen/akita"
repository = "https://github.com/wslongchen/akita"
license = "MIT"

[dependencies]
akita_derive = {version = "0.1.0", optional = true, path = "./akita_derive"}
mysql = "19.0.1"
r2d2 = "0.8.9"
chrono = { version = "0.4", features = ["serde"]}


[dev-dependencies]
akita_derive = { version = "0.1.0", path = "./akita_derive" }

[package.metadata.playground]
features = ["derive"]

[package.metadata.docs.rs]
targets = ["x86_64-unknown-linux-gnu"]


### FEATURES #################################################################

[features]
default = ["derive"]

# Provide derive(Table) macros.
derive = ["akita_derive"]

# Provide r2d2 pool.
r2d2_pool = []

# Provide impls for HashMap<K, V>.
# Requires a dependency on the Rust standard library.
std = []
